### ISSUE TITLE
AttributeError: Can't get attribute 'Individual' on <module 'deap.creator'

### ISSUE THREAD

**Issue by 943fansi** [mohyunho/ENAS-PdM#1]
hi,mohyunho! I am interesting with your work.
when I run launcher.py but get this error,
[AttributeError: Can't get attribute 'Individual' on <module 'deap.creator']
how to solve it?

more info is:
[41214 rows x 18 columns]
pre-processing is successfully completed
Empty DataFrame
Columns: [idx, stop_epoch, window_length, n_filters, kernel_size, n_conv_layer, LSTM1_units, LSTM2_units, n_window, val_rmse, val_score, rmse_combined, score_combined, AIC, train_loss, mle_term, params_term, geno_list]
Index: []

I try to this by search on the Internet,there is a reference answer but it didn't help me.The ref link is
https://stackoverflow.com/questions/61065222/python-deap-and-multiprocessing-on-windows-attributeerror
by the way ,my computer is also windows system.
could you help me with this problem?

**Comment by mohyunho** [comment]
Hi, 943fansi.  Thanks for reaching out. 
To find the reason, I've tried to run the code, but i could not get the same error. So, please understand that i cannot provide you an exact answer to address the problem.

Based on the discussion in the forum you shared, i guess that the error likely comes from the code related to the multiprocessing via pathos. I used a pathos multiprocessing in my code, and currently the variable 'jobs' is set to '2' for that. 
So, i suggest you to set this to '1' to deactivate the multiprocessing or directly remove the pathos related codes in 'evolutionary_algorithm.py'.

If the answer would not be helpful and the problem persists, please let me know.

**Comment by 943fansi** [comment]
> Hi, 943fansi. Thanks for reaching out. To find the reason, I've tried to run the code, but i could not get the same error. So, please understand that i cannot provide you an exact answer to address the problem.
> 
> Based on the discussion in the forum you shared, i guess that the error likely comes from the code related to the multiprocessing via pathos. I used a pathos multiprocessing in my code, and currently the variable 'jobs' is set to '2' for that. So, i suggest you to set this to '1' to deactivate the multiprocessing or directly remove the pathos related codes in 'evolutionary_algorithm.py'.
> 
> If the answer would not be helpful and the problem persists, please let me know.

Thank you for your advice.Your suggestion is very useful, it does work as you guess when 'jobs' is set to '1'.

Another problem is something about gpu on training.
【Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR】
Could you tell me the Equipment you used for this code?
I notice that you set 5014 in the code,but my GPU is RTX2060  has only 6GB.I guess the error occurs because of Insufficient  memory.So I change 5014 to 3072,Will this change affect the experimental results？

 
gpus = tf.config.experimental.list_physical_devices('GPU')
        if gpus:
            try:

                # Currently, memory growth needs to be the same across GPUs
                for gpu in gpus:
                    # tf.config.experimental.set_memory_growth(gpu, True)
                    tf.config.experimental.set_virtual_device_configuration(gpu, [
                        tf.config.experimental.VirtualDeviceConfiguration(memory_limit=5014)])
                logical_gpus = tf.config.experimental.list_logical_devices('GPU')
                # print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
            except RuntimeError as e:
                # Memory growth must be set before GPUs have been initialized
                print(e)

**Comment by mohyunho** [comment]
I'm happy to hear that you could handle the issue with that.
The GPU i used is NVIDIA TITAN Xp which has 12GB. I didn't manually set memory_limit to '5014', and do not know how does it affect to our computation.
But, if you can run the code with the limit of 3072 and without changing any tunable parameters, then you can obtain an optimized network as an output ( the discovered and selected architecture can be slightly different depending on the computational resources you used because the fitness of each individual can be different too).

You can somewhat mitigate the memory issue with changing the batch size, but it may affect the training time and the final results. 

One last thing want to share is that i used a TF determinism which enables to have reproducible results from GPU computation. But, in certain case, it can cause ineffective memory use and slow down the training. So, i recommend you to remove "os.environ['TF_DETERMINISTIC_OPS'] = '1'" any of the files in the repository unless you have to get an strictly reproducible results.

**Comment by 943fansi** [comment]
Thanks for your answers and sharing. Your patient and detailed reply is very helpful to me. Thank you again sincerely!
