### ISSUE TITLE
Confused about The seq_length and window_length ，can I just use window_length to segment ?I try to use Optimized network structure to train data,it seems hard to train ,could you please provide me a single py about mulit-head cnn-lstm model? 

### ISSUE THREAD

**Issue by 943fansi** [mohyunho/ENAS-PdM#2]

**Comment by mohyunho** [comment]
HI, 943fansi. In  this work, we apply first level time window approach to have 'sequence' and then the 2nd level time window is considered to extract the segments from the sequence. I know this approach is somewhat confusing but this is necessary for the multi-head CNN-LSTM. (for further details, please check our paper, https://www.sciencedirect.com/science/article/pii/S1568494621003975)
In the 'network_training.py' file, you can check how i implement the network in TensorFlow-Kreas. 
If you feel this is too complicated and want to avoid, then you can use either 1D-CNN (multi-channel) or LSTM, instead of the CNN-LSTM. In that case, you only need to consider a time window.

**Comment by 943fansi** [comment]
Hi, mohyunho.Thanks for your reply. This reply does not contain any questions.
I debug the code ,the original input is 4d tensor ,(batch_szie, n_window, window_lenth, sensor_dim), For each head, the input shape is (batch_szie, n_window, window_lenth, 1),output shape is (batch_szie, n_window, 28), then merge as (batch_szie, n_window, 28*14) to be the input of lstm.
 I am a novice in deep learning. I am not familiar with tensorflow and have encountered some difficulties.If it brings you some trouble, say sorry here.
Wish you a happy life.

**Comment by mohyunho** [comment]
No problem at all. When you have any questions, please let me know.
